package com.example.bibliotekdb3;

import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.control.Alert;  //M
import javafx.scene.control.TableView; //M
import javafx.scene.control.TextField; //M
import javafx.scene.control.TableColumn; //M

import java.io.IOException;
import java.sql.*;

public class xSearchWloginController {
    private Connection conn = DatabaseConnector.getConnection();

    String currentUser; // Mazkin

    @FXML
    private MenuItem back;

    @FXML
    private Button borrow;

    @FXML
    private MenuItem close;

    @FXML
    private Button myAccount;

    @FXML
    private Button searchButton;

    @FXML
    private TextField searchField;

    @FXML
    private TableView searchResults;


    @FXML
    public void searchDB() {

        String searchStr = searchField.getText();

        try {

            PreparedStatement stmt = conn.prepareStatement
                    ("SELECT * FROM artikel WHERE artikelNr LIKE ? OR titel LIKE ? OR artist LIKE ? OR utgava LIKE ? OR artikelGenre LIKE ? OR artikelKategori LIKE ? OR isbn LIKE ?");
            stmt.setString(1, "%" + searchStr + "%");
            stmt.setString(2, "%" + searchStr + "%");
            stmt.setString(3, "%" + searchStr + "%");
            stmt.setString(4, "%" + searchStr + "%");
            stmt.setString(5, "%" + searchStr + "%");
            stmt.setString(6, "%" + searchStr + "%");
            stmt.setString(7, "%" + searchStr + "%");
            ResultSet rs = stmt.executeQuery();
            // Create table columns based on metadata of result set
            searchResults.getColumns().clear(); // Remove existing columns
            ResultSetMetaData rsmd = rs.getMetaData();
            int numCols = rsmd.getColumnCount();
            for (int i = 0; i < numCols; i++) {
                final int colIdx = i;
                TableColumn<ObservableList<String>, String> column = new TableColumn<>(rsmd.getColumnName(i + 1));
                column.setCellValueFactory(param -> new ReadOnlyObjectWrapper<>(param.getValue().get(colIdx)));
                searchResults.getColumns().add(column);
            }

            // Add data to table
            ObservableList<ObservableList<String>> data = FXCollections.observableArrayList();
            while (rs.next()) {
                ObservableList<String> row = FXCollections.observableArrayList();
                for (int i = 1; i <= numCols; i++) {
                    row.add(rs.getString(i));
                }
                data.add(row);
            }
            searchResults.setItems(data);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    @FXML
    public void borrow() {
        // Get the current user
        String currentUser = UserSession.getCurrentUser();  //Mazkin
        System.out.println("Current user: " + currentUser);   //Mazkin

        ObservableList<String> selectedItem = (ObservableList<String>) searchResults.getSelectionModel().getSelectedItem();
        if (selectedItem != null) {
            String artikelNr = selectedItem.get(0);


            if (currentUser != null) { //Mazkin

                String anvandareNr = currentUser; //Mazkin
                try {
                    // Insert into lan table
                    PreparedStatement stmt1 = conn.prepareStatement("INSERT INTO lan (anvandareNr) VALUES (?)", Statement.RETURN_GENERATED_KEYS);
                    stmt1.setString(1, anvandareNr);
                    stmt1.executeUpdate();

                    // Get the lanNr generated by the previous insert
                    ResultSet rs = stmt1.getGeneratedKeys();
                    rs.next();
                    int lanNr = rs.getInt(1);

                    // Insert into lanartikel table
                    PreparedStatement stmt2 = conn.prepareStatement("INSERT INTO lanartikel (lanNr, artikelNr) VALUES (?, ?)");
                    stmt2.setInt(1, lanNr);
                    stmt2.setString(2, artikelNr);
                    stmt2.executeUpdate();

                    System.out.println("Successfully borrowed item with artikelNr: " + artikelNr + " to anvandareNr: " + anvandareNr);
                } catch (SQLException e) {
                    e.printStackTrace();
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("Error");
                    alert.setHeaderText("Unable to borrow item");
                    alert.setContentText("An error occurred while borrowing the item.");
                    alert.showAndWait();
                }

          /*  String sab = selectedItem.get(1);
            String titel = selectedItem.get(2);
            String artist = selectedItem.get(3);
            String utgava = selectedItem.get(4);
            String artikelGenre = selectedItem.get(5);
            String artikelKategori = selectedItem.get(6);
            String isbn = selectedItem.get(7);
            String statusTyp = selectedItem.get(8);

            System.out.println("artikelNr: " + artikelNr);
            System.out.println("sab: " + sab);
            System.out.println("titel: " + titel);
            System.out.println("artist: " + artist);
            System.out.println("utgava: " + utgava);
            System.out.println("artikelGenre: " + artikelGenre);
            System.out.println("artikelKategori: " + artikelKategori);
            System.out.println("isbn: " + isbn);
            System.out.println("statusTyp: " + statusTyp);
            System.out.println("logged in as: " + username );
            System.out.println("--------------------------");*/

            }
        } else {
            //No item is selected, show an error message to the user
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText(null);
            alert.setContentText("Please select an item to borrow.");
            alert.showAndWait();
        }
    }

    public String getCurrentUser() {
        return currentUser;
    }       //Mazkin


    @FXML
    public void myAccount() throws IOException {

       // App.setRoot("account.fxml");
        App.setRoot("addRemoveEdit.fxml");

    }


    @FXML
    public void back() throws IOException {

        App.setRoot("startPage.fxml");

    }

    @FXML
    public void close() {
        System.exit(0);
    }



}
